targets:
  $default:
    builders:
      riverpod_generator:
        generate_for:
          - lib/**/*.dart
        options:
          # Riverpod code generation options
          riverpod_generator:
            provider_name_prefix: ""
            provider_name_suffix: "Provider"

      freezed:
        generate_for:
          - lib/**/*.dart

      json_serializable:
        generate_for:
          - lib/**/*.dart
        options:
          any_map: false
          checked: false
          constructor: ""
          create_factory: true
          create_to_json: true
          disallow_unrecognized_keys: false
          explicit_to_json: true
          field_rename: none
          generic_argument_factories: false
          ignore_unannotated: false
          include_if_null: false

      drift_dev:
        options:
          store_date_time_values_as_text: true
          generate_connect_constructor: true
